name: TheListingEngine
favicon: null
layout_spectrum: 0.8445932287722826
typography_spectrum: 0.9809017663355917
title: The Listing Engine
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#1c1819'
    - '#70716c'
    - '#deb062'
    - '#fef8a7'
    - '#cf8a44'
  brandStrength: 0.7871596047189087
  lightness: 1
  saturation: 0
  rhythmicContrast: 0.5
purpose: []
