name: TheListingEngine
favicon: null
layout_spectrum: 0
typography_spectrum: 0.19957
title: The Listing Engine
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#2c1f02'
    - '#e9edca'
    - '#00ffff'
    - '#ea580f'
    - '#4b7a21'
  brandStrength: 1
  lightness: 0
  saturation: 0.125
  rhythmicContrast: 0
purpose: []
