name: TheListingEngine
favicon: null
layout_spectrum: 0.49962
typography_spectrum: 0
title: The Listing Engine
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#312204'
    - '#eceed1'
    - '#e56720'
    - '#2dfffe'
    - '#59832b'
  brandStrength: 1
  lightness: 0.5
  saturation: 0.0625
  rhythmicContrast: 1
purpose: []
